#ifndef MNIST_TEST_H

#define MNIST_CLASS_COUNT 10
#define MNIST_DIMENSION 28
#define MNIST_DATA_SIZE (MNIST_DIMENSION * MNIST_DIMENSION)
#define MNIST_MAX_PIXEL_VALUE 255.0f

#define MNIST_TEST_H
#endif